[package]
name = "traversev"
version = "0.1.0-alpha.1"
description = """
A memory-hard proof-of-work scheme for trustless and permissioned proofs.
"""
authors = ["Determination Labs Team"]
license = "MIT"
documentation = "https://docs.rs/traversev"
homepage = "https://github.com/0x44-labs/rs-traversev"
repository = "https://github.com/0x44-labs/rs-traversev"
keywords = ["pow", "proof-of-work", "memory-hard", "blake3", "salsa20"]
categories = ["cryptography", "algorithms"]
readme = "README.md"
edition = "2024"

[dependencies]
blake3 = "1.8.7"
salsa20 = "0.11.0"
subtle = "2.6.1"
