#![doc = include_str!("../README.md")]
//! ## Example
//! ```
//! use traversev::{Params, TraverseV};
//!
//! fn main() {
//!     let params = Params::new(12 * 1024, 3, 8, 12).unwrap();
//!     let context = "65daysofstatic";
//!
//!     // Build a trustless instance
//!     let miner = TraverseV::new_trustless(context, params);
//!
//!     // Mine for a trustless proof over some input
//!     let input = b"65 Doesn't Understand You";
//!     let proof = miner.mine(input);
//!
//!     // Any trustless instance with the same configuration can verify
//!     let verifier = TraverseV::new_trustless(context, params);
//!     assert!(verifier.verify(input, proof));
//!
//!     // Build a permissioned instance with a shared secret
//!     let secret = b"One Time for All Time";
//!     let miner = TraverseV::new_permissioned(secret, context, params);
//!
//!     // A trustless instance cannot verify a permissioned proof
//!     let proof = miner.mine(input);
//!     assert!(!verifier.verify(input, proof));
//! }
//! ```
//!
//! ## Features
//!
//! The `zeroize` feature (disabled by default) implements `ZeroizeOnDrop` for
//! TraverseV, and zeroises intermediate values.
mod block;
mod errors;
mod memory;
mod mix;
mod params;

use blake3::Hasher;
use subtle::{Choice, ConstantTimeEq};
#[cfg(feature = "zeroize")]
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::block::{BLOCK_SIZE, Block, WORDS};
pub use crate::errors::TraverseVErr;
pub use crate::memory::Mode;
use crate::memory::{fill, initial_blocks};
use crate::mix::iter_mix;
pub use crate::params::Params;

macro_rules! fill_memory {
    ($mode: expr, $secret:expr, $context:expr, $params:expr) => {{
        let q = $params.m_cost() as usize;
        let t = $params.t_cost() as usize;

        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let (mut b0, mut b1) = initial_blocks(
            $mode,
            $params.m_cost(),
            $params.t_cost(),
            $params.e_cost(),
            $params.n_cost(),
            $context,
            $secret,
        );

        let mut v = vec![Block::from_words([0; WORDS]); q];
        v[0].copy_from(&b0);
        v[1].copy_from(&b1);

        #[cfg(feature = "zeroize")]
        {
            b0.zeroize();
            b1.zeroize();
        }

        fill(&mut v, q, t);

        v
    }};
}

macro_rules! context_tag {
    ($context:expr) => {{
        let mut hasher = Hasher::new();
        hasher.update($context.as_bytes());
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut hash = hasher.finalize();
        let tag: [u8; 32] = hash.into();

        #[cfg(feature = "zeroize")]
        {
            hasher.zeroize();
            hash.zeroize();
        }

        tag
    }};
}

/// TraverseV proof-of-work instance.
///
/// Construction fills a memory buffer using a fill adapted from Argon2d. Each
/// block is derived from its predecessor and a pseudorandomly selected earlier
/// block via Argon2's BLAKE2b-based compression function, repeated over
/// multiple passes.
///
/// Mining iteratively searches for a proof that satisfies this instance's
/// difficulty. Each candidate is evaluated by applying rounds of the
/// scryptROMix algorithm's second loop, mixing memory blocks into the
/// computation via Salsa20/8-based BlockMix.
#[cfg_attr(test, derive(Clone))]
pub struct TraverseV {
    mode: Mode,
    buffer: Vec<Block>,
    tag: [u8; 32],
    key: Option<[u8; 32]>,
    params: Params,
}

impl TraverseV {
    /// Build a new trustless `TraverseV` instance.
    ///
    /// Creates and fills a memory buffer, and stores this instance's
    /// application context and parameters.
    ///
    /// Proofs generated by this instance are trustless, meaning they are
    /// verifiable by any instance sharing the same application context and
    /// parameters.
    pub fn new_trustless(context: impl Into<String>, params: Params) -> Self {
        let context = context.into();
        let v = fill_memory!(Mode::Trustless, None, &context, params);
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut tag = context_tag!(context);

        let this = Self {
            mode: Mode::Trustless,
            buffer: v,
            tag,
            key: None,
            params,
        };

        #[cfg(feature = "zeroize")]
        tag.zeroize();

        this
    }

    /// Build a new permissioned `TraverseV` instance.
    ///
    /// Creates and fills a memory buffer, and stores this instance's secret,
    /// application context, and parameters.
    ///
    /// Proofs generated by this instance are permissioned, meaning they are
    /// verifiable only by instances sharing the same application context,
    /// parameters, and shared secret.
    pub fn new_permissioned(
        secret: &[u8],
        context: impl Into<String>,
        params: Params,
    ) -> Self {
        let context = context.into();
        let v =
            fill_memory!(Mode::Permissioned, Some(secret), &context, params);
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut tag = context_tag!(context);

        let mut hasher = Hasher::new_derive_key(&context);
        hasher.update(secret);
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut hash = hasher.finalize();
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut key: [u8; 32] = hash.into();

        let this = Self {
            mode: Mode::Permissioned,
            buffer: v,
            tag,
            key: Some(key),
            params,
        };

        #[cfg(feature = "zeroize")]
        {
            tag.zeroize();
            hasher.zeroize();
            hash.zeroize();
            key.zeroize();
        }

        this
    }

    /// Mine for a proof satisfying this instance's configured difficulty.
    ///
    /// Iteratively searches for candidates until one satisfies the difficulty.
    /// Runtime is unbounded on high difficulties.
    ///
    /// A [trustless](Self::new_trustless) instance mines for a trustless
    /// proof, and a [permissioned](Self::new_permissioned) instance mines for
    /// a permissioned proof.
    pub fn mine<T, N, I>(&self, input: &[u8], mut counter: T, increment: I) -> N
    where
        T: core::ops::AddAssign<I> + Into<N> + Copy,
        N: num_traits::ToBytes + Copy,
        I: Copy,
    {
        let mut hasher = Hasher::new();
        hasher.update(input);
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut hash = hasher.finalize();
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut prefix: [u8; 32] = hash.into();

        #[cfg(feature = "zeroize")]
        {
            hasher.zeroize();
            hash.zeroize();
        }

        let proof = loop {
            let v: N = counter.into();

            #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
            let mut candidate = self.evaluate(&prefix, v);
            let satisfied = self.check_n(&candidate);

            #[cfg(feature = "zeroize")]
            candidate.zeroize();

            // Break loop when the constraint is satisfied
            if bool::from(satisfied) {
                break v;
            }

            counter += increment
        };

        #[cfg(feature = "zeroize")]
        prefix.zeroize();

        proof
    }

    /// Verify that a proof satisfies this instance's difficulty.
    ///
    /// Successful verification requires the verifying instance's configuration
    /// to match the one the proof was mined with.
    ///
    /// A [trustless](Self::new_trustless) instance can only verify trustless
    /// proofs, and a and a [permissioned](Self::new_permissioned) instance can
    /// only verify permissioned proofs.
    pub fn verify<N: num_traits::ToBytes + Copy>(
        &self,
        input: &[u8],
        proof: N,
    ) -> bool {
        let mut hasher = Hasher::new();
        hasher.update(input);
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut hash = hasher.finalize();
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut prefix: [u8; 32] = hash.into();

        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut candidate = self.evaluate(&prefix, proof);
        let satisfied = self.check_n(&candidate);

        #[cfg(feature = "zeroize")]
        {
            hasher.zeroize();
            hash.zeroize();
            prefix.zeroize();
            candidate.zeroize();
        }

        bool::from(satisfied)
    }

    /// This `TraverseV` instance's mode, as either trustless or permissioned.
    pub const fn mode(&self) -> Mode {
        self.mode
    }

    fn evaluate<N: num_traits::ToBytes + Copy>(
        &self,
        prefix: &[u8; 32],
        v: N,
    ) -> [u8; 32] {
        let mut hasher = if let Some(key) = &self.key {
            Hasher::new_keyed(key)
        } else {
            Hasher::new()
        };
        hasher.update(prefix);
        hasher.update(&v.to_le_bytes().as_ref());
        hasher.update(&self.tag);

        let mut bytes = [0u8; BLOCK_SIZE];
        let mut reader = hasher.finalize_xof();
        reader.fill(&mut bytes);
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut x = Block::from_bytes(&bytes);

        let q = self.params.m_cost() as usize;
        let k = self.params.e_cost() as usize;
        x = iter_mix(x, &self.buffer, q, k);
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut x_bytes = x.to_bytes();
        #[cfg_attr(not(feature = "zeroize"), allow(unused_mut))]
        let mut hash = blake3::hash(&x_bytes);
        let candidate: [u8; 32] = hash.into();

        #[cfg(feature = "zeroize")]
        {
            hasher.zeroize();
            reader.zeroize();
            x.zeroize();
            x_bytes.zeroize();
            hash.zeroize();
        }

        candidate
    }

    fn check_n(&self, candidate: &[u8; 32]) -> Choice {
        let n = self.params.n_cost() as u8;
        let bytes = n / 8;
        let bits = n % 8;

        // Verify first N bytes are zero, following N bits are zero
        let mut satisfied = Choice::from(1u8);
        for i in 0..bytes {
            satisfied &= candidate[i as usize].ct_eq(&0u8);
        }
        if bits > 0 {
            let mask = (0xFF << (8 - bits)) as u8;
            satisfied &= (candidate[bytes as usize] & mask).ct_eq(&0u8);
        }

        satisfied
    }
}

#[cfg(feature = "zeroize")]
impl Drop for TraverseV {
    fn drop(&mut self) {
        self.buffer.zeroize();
        self.tag.zeroize();
        self.key.zeroize();
    }
}

#[cfg(feature = "zeroize")]
impl ZeroizeOnDrop for TraverseV {}

#[cfg(test)]
mod tests {
    use super::*;

    const CONTEXT: &str = "TRAVERSEV_TEST";
    const SECRET: &[u8] = b"This is a secret.";
    const INPUT: &[u8] = b"Some mining input.";

    /// Parameters for testing.
    ///
    /// 8 KiB memory, 2 memory fill iterations, 2 evaluation mixing rounds,
    /// and a difficulty of 12.
    fn params() -> Params {
        Params::new(8, 2, 2, 12).expect("test parameters are valid")
    }

    /// Memory buffer constructed manually from `initial_blocks` and `fill`.
    fn expected_buffer(mode: Mode, secret: Option<&[u8]>) -> Vec<Block> {
        let q = 8_usize;
        let t = 2_usize;

        #[rustfmt::skip]
        let (b0, b1) = initial_blocks(
            mode,
            q as u32,
            t as u32,
            2,
            12,
            CONTEXT,
            secret
        );

        let mut v = vec![Block::from_words([0; WORDS]); q];
        v[0].copy_from(&b0);
        v[1].copy_from(&b1);
        fill(&mut v, q, t);

        v
    }

    #[test]
    fn new_trustless_builds_instance() {
        let params = params();
        let tv = TraverseV::new_trustless(CONTEXT, params);

        let tag = blake3::hash(CONTEXT.as_bytes());
        let buffer = expected_buffer(Mode::Trustless, None);

        assert_eq!(tv.mode() as u8, Mode::Trustless as u8);
        assert!(tv.key.is_none());
        assert_eq!(tv.tag, *tag.as_bytes());
        assert_eq!(tv.params, params);
        assert_eq!(tv.buffer, buffer);
    }

    #[test]
    fn new_permissioned_builds_instance() {
        let params = params();
        let tv = TraverseV::new_permissioned(SECRET, CONTEXT, params);

        let tag = blake3::hash(CONTEXT.as_bytes());
        let buffer = expected_buffer(Mode::Permissioned, Some(SECRET));

        assert_eq!(tv.mode() as u8, Mode::Permissioned as u8);
        assert_eq!(tv.key, Some(blake3::derive_key(CONTEXT, SECRET)));
        assert_eq!(tv.tag, *tag.as_bytes());
        assert_eq!(tv.params, params);
        assert_eq!(tv.buffer, buffer);
    }

    #[test]
    fn trustless_proof_verifies() {
        let miner = TraverseV::new_trustless(CONTEXT, params());
        let verifier = miner.clone();

        let proof: u128 = miner.mine(INPUT, 0u128, 1);
        assert!(verifier.verify(INPUT, proof));
    }

    #[test]
    fn permissioned_proof_verifies() {
        let miner = TraverseV::new_permissioned(SECRET, CONTEXT, params());
        let verifier = miner.clone();

        let proof: u128 = miner.mine(INPUT, 0u128, 1);
        assert!(verifier.verify(INPUT, proof));
    }

    #[test]
    fn trustless_rejects_permissioned_proof() {
        // At n = 12 a wrong instance accepts a proof with probability 1/4096.
        let miner = TraverseV::new_permissioned(SECRET, CONTEXT, params());
        let verifier = TraverseV::new_trustless(CONTEXT, params());

        let proof: u128 = miner.mine(INPUT, 0u128, 1);
        assert!(!verifier.verify(INPUT, proof));
    }

    #[test]
    fn verify_rejects_unsatisfied_difficulty() {
        let params = Params::new(2 * 1024, 2, 2, 255)
            .expect("test parameters are valid");

        let verifier = TraverseV::new_trustless(CONTEXT, params);
        assert!(!verifier.verify(INPUT, 0u128));
    }
}
