mod constants;
mod errors;
mod memory;
mod nonce;
mod params;
mod traverse;

use blake3::Hasher;
use subtle::{Choice, ConstantTimeEq};

use crate::constants::BLOCK_SIZE;
use crate::memory::{fill, initial_blocks};
use crate::nonce::Nonce;
pub use crate::params::Params;
use crate::traverse::dependency_chain;

macro_rules! fill_memory {
    ($secret:expr, $context:expr, $params:expr) => {{
        let secret: Option<&[u8]> = $secret;

        let q = $params.m_cost() as usize;
        let t = $params.t_cost() as usize;

        let mut v = vec![0u8; q * BLOCK_SIZE];
        let (b0, b1) = initial_blocks(
            secret.unwrap_or(&[]),
            $params.m_cost(),
            $params.t_cost(),
            $params.d_cost(),
            $params.n_cost(),
        );
        v[0..BLOCK_SIZE].copy_from_slice(&b0);
        v[BLOCK_SIZE..2 * BLOCK_SIZE].copy_from_slice(&b1);
        fill(&mut v, q, t);

        v
    }};
}

/// TraverseV proof-of-work instance.
///
/// Construction fills a memory buffer using a fill adapted from Argon2d. Each
/// block is derived from its predecessor and a pseudorandomly selected earlier
/// block via Argon2's BLAKE2b-based compression function, repeated over
/// multiple passes.
///
/// Mining iteratively searches for a nonce that satisfies this instance's
/// difficulty. Each candidate nonce is evaluated by applying rounds of the
/// scryptROMix algorithm's second loop, mixing memory blocks into the
/// computation via Salsa20/8-based BlockMix.
pub struct TraverseV {
    buffer: Vec<u8>,
    context_tag: [u8; 32],
    secret_key: Option<[u8; 32]>,
    params: Params,
}

impl TraverseV {
    /// Build a new trustless `TraverseV` instance.
    ///
    /// Creates and fills a memory buffer, and stores this instance's
    /// application context and parameters.
    ///
    /// Proofs generated by this instance are trustless, meaning they are
    /// verifiable by any instance of the same application context and
    /// configuration.
    pub fn new_trustless(context: &str, params: Params) -> Self {
        let v = fill_memory!(None, context, params);

        let mut hasher = Hasher::new();
        hasher.update(context.as_bytes());
        let context_tag: [u8; 32] = hasher.finalize().into();

        Self {
            buffer: v,
            context_tag,
            secret_key: None,
            params,
        }
    }

    /// Build a new permissioned `TraverseV` instance.
    ///
    /// Creates and fills a memory buffer, and stores this instance's secret,
    /// application context, and parameters.
    ///
    /// Proofs generated by this instance are permissioned, meaning they are
    /// verifiable by any instance of the same application context,
    /// configuration, and holding the same shared secret.
    pub fn new_permissioned(
        secret: &[u8],
        context: &str,
        params: Params,
    ) -> Self {
        let v = fill_memory!(Some(secret), context, params);

        let mut hasher = Hasher::new();
        hasher.update(context.as_bytes());
        let context_tag: [u8; 32] = hasher.finalize().into();

        let mut hasher = Hasher::new_derive_key(context);
        hasher.update(secret);
        let secret_key: [u8; 32] = hasher.finalize().into();

        Self {
            buffer: v,
            context_tag,
            secret_key: Some(secret_key),
            params,
        }
    }

    /// Mine for a nonce value satisfying this instance's difficulty.
    ///
    /// Iteratively searches for candidates until one satisfies the difficulty.
    /// Runtime is unbounded on high difficulties.
    pub fn mine(&self, input: &[u8]) -> u128 {
        let mut nonce = Nonce::new();

        let mut hasher = Hasher::new();
        hasher.update(input);
        let prefix: [u8; 32] = hasher.finalize().into();

        loop {
            let nonce_u128 = u128::from(nonce);

            let candidate = self.evaluate(&prefix, nonce_u128);
            let satisfied = self.check_n(&candidate);

            // Break loop when the constraint is satisfied
            if bool::from(satisfied) {
                return nonce_u128;
            }

            nonce += 1
        }
    }

    /// Check if a nonce value satisfies this instance's difficulty.
    pub fn verify(&self, input: &[u8], nonce: u128) -> bool {
        let mut hasher = Hasher::new();
        hasher.update(input);
        let prefix: [u8; 32] = hasher.finalize().into();

        let candidate = self.evaluate(&prefix, nonce);
        let satisfied = self.check_n(&candidate);

        bool::from(satisfied)
    }

    fn evaluate(&self, prefix: &[u8; 32], nonce: u128) -> [u8; 32] {
        let mut hasher = if let Some(key) = &self.secret_key {
            Hasher::new_keyed(key)
        } else {
            Hasher::new()
        };
        hasher.update(prefix);
        hasher.update(&u128::from(nonce).to_le_bytes());
        hasher.update(&self.context_tag);

        let mut x = [0u8; BLOCK_SIZE];
        let mut reader = hasher.finalize_xof();
        reader.fill(&mut x);

        let q = self.params.m_cost() as usize;
        let k = self.params.d_cost() as usize;
        x = dependency_chain(x, &self.buffer, q, k);
        blake3::hash(&x).into()
    }

    fn check_n(&self, candidate: &[u8; 32]) -> Choice {
        let n = self.params.n_cost() as u8;
        let bytes = n / 8;
        let bits = n % 8;

        // Verify first N bytes are zero, following N bits are zero
        let mut satisfied = Choice::from(1u8);
        for i in 0..bytes {
            satisfied &= candidate[i as usize].ct_eq(&0u8);
        }
        if bits > 0 {
            let mask = (0xFF << (8 - bits)) as u8;
            satisfied &= (candidate[bytes as usize] & mask).ct_eq(&0u8);
        }

        satisfied
    }
}
