mod common;
mod errors;
mod memory;
mod nonce;
mod params;
mod traverse;

use blake3::Hasher;
use subtle::{Choice, ConstantTimeEq};

use crate::common::{BLOCK_SIZE, Mode};
use crate::memory::{fill, initial_blocks};
use crate::nonce::Nonce;
pub use crate::params::Params;
use crate::traverse::dependency_chain;

macro_rules! fill_memory {
    ($mode: expr, $secret:expr, $context:expr, $params:expr) => {{
        let q = $params.m_cost() as usize;
        let t = $params.t_cost() as usize;

        let mut v = vec![0u8; q * BLOCK_SIZE];
        let (b0, b1) = initial_blocks(
            $mode,
            $params.m_cost(),
            $params.t_cost(),
            $params.e_cost(),
            $params.n_cost(),
            $context,
            $secret,
        );
        v[0..BLOCK_SIZE].copy_from_slice(&b0);
        v[BLOCK_SIZE..2 * BLOCK_SIZE].copy_from_slice(&b1);
        fill(&mut v, q, t);

        v
    }};
}

macro_rules! context_tag {
    ($context:expr) => {{
        let mut hasher = Hasher::new();
        hasher.update($context.as_bytes());
        let tag: [u8; 32] = hasher.finalize().into();

        tag
    }};
}

/// TraverseV proof-of-work instance.
///
/// Construction fills a memory buffer using a fill adapted from Argon2d. Each
/// block is derived from its predecessor and a pseudorandomly selected earlier
/// block via Argon2's BLAKE2b-based compression function, repeated over
/// multiple passes.
///
/// Mining iteratively searches for a proof that satisfies this instance's
/// difficulty. Each candidate is evaluated by applying rounds of the
/// scryptROMix algorithm's second loop, mixing memory blocks into the
/// computation via Salsa20/8-based BlockMix.
pub struct TraverseV {
    mode: Mode,
    buffer: Vec<u8>,
    tag: [u8; 32],
    key: Option<[u8; 32]>,
    params: Params,
}

impl TraverseV {
    /// Build a new trustless `TraverseV` instance.
    ///
    /// Creates and fills a memory buffer, and stores this instance's
    /// application context and parameters.
    ///
    /// Proofs generated by this instance are trustless, meaning they are
    /// verifiable by any instance sharing the same application context and
    /// configuration.
    pub fn new_trustless(context: &str, params: Params) -> Self {
        let v = fill_memory!(Mode::Trustless, None, context, params);
        let tag = context_tag!(context);

        Self {
            mode: Mode::Trustless,
            buffer: v,
            tag,
            key: None,
            params,
        }
    }

    /// Build a new permissioned `TraverseV` instance.
    ///
    /// Creates and fills a memory buffer, and stores this instance's secret,
    /// application context, and parameters.
    ///
    /// Proofs generated by this instance are permissioned, meaning they are
    /// verifiable only by instances sharing the same application context,
    /// configuration, and shared secret.
    pub fn new_permissioned(
        secret: &[u8],
        context: &str,
        params: Params,
    ) -> Self {
        let v = fill_memory!(Mode::Permissioned, Some(secret), context, params);
        let tag = context_tag!(context);

        let mut hasher = Hasher::new_derive_key(context);
        hasher.update(secret);
        let key: [u8; 32] = hasher.finalize().into();

        Self {
            mode: Mode::Permissioned,
            buffer: v,
            tag,
            key: Some(key),
            params,
        }
    }

    /// Mine for a proof satisfying this instance's configured difficulty.
    ///
    /// Iteratively searches for candidates until one satisfies the difficulty.
    /// Runtime is unbounded on high difficulties.
    ///
    /// A [trustless](Self::new_trustless) instance mines for a trustless
    /// proof, and a [permissioned](Self::new_permissioned) instance mines for
    /// a permissioned proof.
    pub fn mine(&self, input: &[u8]) -> u128 {
        let mut nonce = Nonce::new();

        let mut hasher = Hasher::new();
        hasher.update(input);
        let prefix: [u8; 32] = hasher.finalize().into();

        loop {
            let proof = u128::from(nonce);

            let candidate = self.evaluate(&prefix, proof);
            let satisfied = self.check_n(&candidate);

            // Break loop when the constraint is satisfied
            if bool::from(satisfied) {
                return proof;
            }

            nonce += 1
        }
    }

    /// Verify that a proof satisfies this instance's difficulty.
    ///
    /// Successful verification requires the verifying instance's configuration
    /// to match the one the proof was mined with.
    ///
    /// A [trustless](Self::new_trustless) instance can only verify trustless
    /// proofs, and a and a [permissioned](Self::new_permissioned) instance can
    /// only verify permissioned proofs.
    pub fn verify(&self, input: &[u8], proof: u128) -> bool {
        let mut hasher = Hasher::new();
        hasher.update(input);
        let prefix: [u8; 32] = hasher.finalize().into();

        let candidate = self.evaluate(&prefix, proof);
        let satisfied = self.check_n(&candidate);

        bool::from(satisfied)
    }

    /// This `TraverseV` instance's mode, as either trustless or permissioned.
    pub const fn mode(&self) -> Mode {
        self.mode
    }

    fn evaluate(&self, prefix: &[u8; 32], proof: u128) -> [u8; 32] {
        let mut hasher = if let Some(key) = &self.key {
            Hasher::new_keyed(key)
        } else {
            Hasher::new()
        };
        hasher.update(prefix);
        hasher.update(&proof.to_le_bytes());
        hasher.update(&self.tag);

        let mut x = [0u8; BLOCK_SIZE];
        let mut reader = hasher.finalize_xof();
        reader.fill(&mut x);

        let q = self.params.m_cost() as usize;
        let k = self.params.e_cost() as usize;
        x = dependency_chain(x, &self.buffer, q, k);
        blake3::hash(&x).into()
    }

    fn check_n(&self, candidate: &[u8; 32]) -> Choice {
        let n = self.params.n_cost() as u8;
        let bytes = n / 8;
        let bits = n % 8;

        // Verify first N bytes are zero, following N bits are zero
        let mut satisfied = Choice::from(1u8);
        for i in 0..bytes {
            satisfied &= candidate[i as usize].ct_eq(&0u8);
        }
        if bits > 0 {
            let mask = (0xFF << (8 - bits)) as u8;
            satisfied &= (candidate[bytes as usize] & mask).ct_eq(&0u8);
        }

        satisfied
    }
}
